behaviors:
  MarbleMaze:
    trainer_type: sac
    hyperparameters:
      batch_size: 256
      buffer_size: 500000
      learning_rate: 0.0003
      buffer_init_steps: 0
      tau: 0.005
      steps_per_update: 20.0
      save_replay_buffer: false
      init_entcoef: 1.0
      reward_signal_steps_per_update: 20.0
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 8000000
    time_horizon: 128
    summary_freq: 50000


